# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nextflow-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 20Gi
#   storageClassName: standard

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nam-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nextflow-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 3Gi
#   storageClassName: standard